### ISSUE TITLE
大佬好，我们的群计划用这个游戏搞个小比赛，希望可以同意（

### ISSUE THREAD

**Issue by MistEO** [Deyi233/EatRui#2]
因为没找到您的邮箱，只好发在 ISSUE 里了orz

比赛规则原文：

> 春节期间内卷比赛！！！
换游戏了，试玩地址： https://deyi233.github.io/EatRui/index.html
仅允许使用图色脚本（opencv可以，ocr可以，按键精灵之类的也没问题），自己手点也算，但禁止使用任何侵入式的外挂程序。最终分数高者获胜！奖品还是一箱黑咖啡
比赛时间是春节期间，现在还未开始。欢迎大家提交代码魔改游戏，加入各种坑！
https://github.com/InvoluteHell/EatRui

**Comment by MistEO** [comment]
顺便打个广告，如果可以的话_(:з」∠)_
群号 672372860
有兴趣的朋友也可以加群参赛2333

**Comment by Deyi233** [comment]
就一小游戏，玩玩图个乐子就行了啦~hxd不用征求同意的~~~
另外开源来自吃掉小鹿乃
然后其实我昨天才知道这个网站，从来没接触过代码。。。就瞎改了改xingye大佬的文字和图片。
